apiVersion: 1

datasources:
  - name: InfluxDB-Telemetry
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: drone_fleet
      defaultBucket: telemetry
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-auth-token
    isDefault: true
    editable: true
