"""initial_v4_schema

Revision ID: 2c546c1e5c55
Revises: 
Create Date: 2026-03-02 14:14:58.056228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c546c1e5c55'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commands',
    sa.Column('cmd_id', sa.Uuid(), nullable=False),
    sa.Column('drone_id', sa.String(length=64), nullable=False),
    sa.Column('command', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('params_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=True),
    sa.Column('client_request_id', sa.String(length=64), nullable=True),
    sa.Column('preflight_snapshot_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('cmd_id')
    )
    op.create_index(op.f('ix_commands_client_request_id'), 'commands', ['client_request_id'], unique=False)
    op.create_index(op.f('ix_commands_drone_id'), 'commands', ['drone_id'], unique=False)
    op.create_index(op.f('ix_commands_status'), 'commands', ['status'], unique=False)
    op.create_table('drone_snapshots',
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('drone_id', sa.String(length=64), nullable=False),
    sa.Column('version_seq', sa.Integer(), nullable=False),
    sa.Column('state_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_index(op.f('ix_drone_snapshots_created_at'), 'drone_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_drone_snapshots_drone_id'), 'drone_snapshots', ['drone_id'], unique=False)
    op.create_table('drones',
    sa.Column('drone_id', sa.String(length=64), nullable=False),
    sa.Column('env', sa.String(length=16), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_telemetry_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('health_label', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('drone_id')
    )
    op.create_index(op.f('ix_drones_env'), 'drones', ['env'], unique=False)
    op.create_index(op.f('ix_drones_health_label'), 'drones', ['health_label'], unique=False)
    op.create_table('missions',
    sa.Column('mission_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('config_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('mission_id')
    )
    op.create_index(op.f('ix_missions_status'), 'missions', ['status'], unique=False)
    op.create_index(op.f('ix_missions_type'), 'missions', ['type'], unique=False)
    op.create_table('operators',
    sa.Column('operator_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('operator_id')
    )
    op.create_index(op.f('ix_operators_username'), 'operators', ['username'], unique=True)
    op.create_table('events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('aggregate_type', sa.String(length=32), nullable=False),
    sa.Column('aggregate_id', sa.String(length=64), nullable=False),
    sa.Column('drone_id', sa.String(length=64), nullable=True),
    sa.Column('command_id', sa.Uuid(), nullable=True),
    sa.Column('mission_id', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('payload_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['command_id'], ['commands.cmd_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_events_aggregate_id'), 'events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_events_aggregate_type'), 'events', ['aggregate_type'], unique=False)
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_drone_id'), 'events', ['drone_id'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_mission_id'), 'events', ['mission_id'], unique=False)
    op.create_index(op.f('ix_events_requested_by'), 'events', ['requested_by'], unique=False)
    op.create_index(op.f('ix_events_severity'), 'events', ['severity'], unique=False)
    op.create_table('tasks',
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('mission_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('drone_ids_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('waypoints_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('formation', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.mission_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_tasks_mission_id'), 'tasks', ['mission_id'], unique=False)
    op.create_index(op.f('ix_tasks_state'), 'tasks', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_state'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_mission_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_events_severity'), table_name='events')
    op.drop_index(op.f('ix_events_requested_by'), table_name='events')
    op.drop_index(op.f('ix_events_mission_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_drone_id'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_index(op.f('ix_events_aggregate_type'), table_name='events')
    op.drop_index(op.f('ix_events_aggregate_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_operators_username'), table_name='operators')
    op.drop_table('operators')
    op.drop_index(op.f('ix_missions_type'), table_name='missions')
    op.drop_index(op.f('ix_missions_status'), table_name='missions')
    op.drop_table('missions')
    op.drop_index(op.f('ix_drones_health_label'), table_name='drones')
    op.drop_index(op.f('ix_drones_env'), table_name='drones')
    op.drop_table('drones')
    op.drop_index(op.f('ix_drone_snapshots_drone_id'), table_name='drone_snapshots')
    op.drop_index(op.f('ix_drone_snapshots_created_at'), table_name='drone_snapshots')
    op.drop_table('drone_snapshots')
    op.drop_index(op.f('ix_commands_status'), table_name='commands')
    op.drop_index(op.f('ix_commands_drone_id'), table_name='commands')
    op.drop_index(op.f('ix_commands_client_request_id'), table_name='commands')
    op.drop_table('commands')
    # ### end Alembic commands ###
